cache:
  address: localhost:6379
  password: ""
  db: 0

loader:
  minio_config:
    endpoint: localhost:9000
    access_key: O/uCyO6FcWvh3OrfeNEURbNYCvadfyPaI1cAKzc0Q+Q=
    secret_key: 2l53yEim336tN2cqtpD1w93F+/gdlxQoaUIs055wS1E=
    bucket_name: wasmninja
  module_loader: fs
  module_directory: "./wasm_modules"
